# Generated by Django 3.0.7 on 2020-06-07 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dj_instaparser', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Account',
            new_name='InstagramAccount',
        ),
    ]
