# Generated by Django 3.0.7 on 2020-06-07 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj_instaparser', '0003_auto_20200607_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='item',
            name='image_url',
            field=models.TextField(blank=True, null=True, verbose_name='Адрес изображения'),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена'),
        ),
    ]
